#!/bin/bash
export CLOG_DIR="C:/Users/TMisko/Tools/ChallengeLog"

usage() {
    echo unknown command: "$@"
    echo "Usage: clog [subcommand]"
    echo -e "\n"
    echo "Options:"
    echo -e "\tstart - start the work timer"
    echo -e "\tstop - stop the work timer"
    echo -e "\tintervals - compute the length of work intervals"
    echo -e "\ttotal - sum the total intervals"
    echo -e "\tupdate - push a status update to github"
    echo -e "\tstatus - check the status of the timer and log"
    echo -e "\trollover - archive the previous week's log and create the new log"
}

start() {
    shift
    CLOG_START_DT=$(date +%F\ %H\:%M\:%S)
    echo "start: $CLOG_START_DT"
    echo "start: $CLOG_START_DT" >> $CLOG_DIR/challenge.log
}

stop() {
    shift
    CLOG_STOP_DT=$(date +%F\ %H\:%M\:%S)
    echo "stop: $CLOG_STOP_DT"
    echo "stop: $CLOG_STOP_DT" >> $CLOG_DIR/challenge.log
}

intervals() {
    shift
    cat $CLOG_DIR/challenge.log | \
    awk '{ print $2" "$3 }' | \
    xargs -I {} date -d "{}" '+%s' | \
    awk '{ if (NR % 2 == 1) { odd = $0; } else { result = $0 - odd; print int(result/36)/100 " hours"; } }'
}

total() {
    shift
    CLOG_TOTAL=intervals | awk '{ sum+=$1 } END { print sum" hours" }'
}

update() {
    total 
    echo Tristan is at $CLOG_TOTAL hours this week\! > $CLOG_DIR/readme.md
    cat $CLOG_DIR/challenge.log | sed -e 's/stop/Tristan stopped work at/' | sed -e 's/start/Tristan started work at/' | sed 's/T/* T/' >> $CLOG_DIR/readme.md
    echo -e "\n"
    cat $CLOG_DIR/challenge.log
    echo -e "\n"
    echo Currently at: $CLOG_TOTAL
    echo -e "\n"
    git -C $CLOG_DIR commit -am "Tristan\'s $(date +%F\ %H\:%M\:%S) status update"
    git -C $CLOG_DIR push origin tristan
}

status() {
    echo "No op for now"
    echo -e "\n"
    echo "To be implemented"
    echo "- Determine current timer status by printing out the last line of the file"
    echo "- Check whether each start has a matching stop in the current log"
    echo "- Check whether the log is stale (whether it needs to be rolled into the archive)"
}

rollover() {
    echo "No op for now"
    echo -e "\n"
    echo "To be implemented"
    echo "- Check the status of the current log, and fail if status fails, suggesting edits to be made"
    echo "- Move the current log into the archive for this week"
    echo "- Check whether the log is stale (whether it needs to be rolled into the archive"
}

declare -A COMMANDS=(
    [main]=usage
    [start]=start
    [stop]=stop
    [intervals]=intervals
    [total]=total
    [update]=update
    [status]=status
    [rollover]=rollover
)

"${COMMANDS[${1:-main}]:-${COMMANDS[main]}}" "$@"
